customer_service_specialist_task:
  description: >
    You are responsible to take the user_requirements and required programing language make sure the requirements are clear and elaborated.
    The user_requirements:
      {requirements}
    The required programing language:
      {programming_language}
    You will take the requirements from the user for the project he want to implement.
    You will make sure the requirements are clear and elaborative with examples and use cases.
    You should cover all missing points in the requirements.
  expected_output: >
    A clear and elaborative requirements based on interaction with the user.
  agent: customer_service_specialist
